version: "3.7"
version: "3.7"
services: 
  front: 
    container_name: front
    image: front
    restart: always
    environment:
      HOST: 0.0.0.0
      PORT: 3000
    ports:
      - '3000:3000' 
